### ISSUE TITLE
change title color

### ISSUE THREAD

**Issue by screen-clucks-2** [jharter1/github-crash-course#1]
ya gotta make it look more rusty:

```css
html {
  font-family: sans-serif;
}

body {
  margin: 0;
  text-align: center;
  background-color: #322e2d;
  color: #f6f0ee;
}

#logo {
  width: 7rem;
  height: 7rem;
  object-fit: contain;
  margin-top: 2rem;
}

h1 {
  color: #cc850c;
}

a {
  color: #fee389;
}

```
